apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-platform-incident-manager
  labels:
    app: alerting-platform-incident-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-platform-incident-manager
  template:
    metadata:
      labels:
        app: alerting-platform-incident-manager
    spec:
      containers:
        - name: alerting-platform-incident-manager
          image: "{{ .Values.gcloud.registryURL }}/alerting-platform-incident-manager:latest"
          imagePullPolicy: Always          
          env:
            - name: PROJECT_ID
              value: {{ .Values.gcloud.projectID | quote }}
              
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | required (print "Missing value: " $key) | quote }}
          {{- end }}

          {{- range $key, $value := .Values.secrets }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-secrets
                  key: {{ $key | quote }}
          {{- end }}