{{- if .Values.notifier.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alerting-platform-notifier-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alerting-platform-notifier
  minReplicas: {{ .Values.notifier.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.notifier.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.notifier.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}