apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-platform-worker
  labels:
    app: alerting-platform-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-platform-worker
  template:
    metadata:
      labels:
        app: alerting-platform-worker
    spec:
      containers:
        - name: alerting-platform-worker
          image: "{{ .Values.gcloud.registryURL }}/alerting-platform-worker:{{ .Values.env.VERSION }}"
          imagePullPolicy: Always
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | required (print "Missing value: " $key) | quote }}
          {{- end }}

          {{- range $key, $value := .Values.secrets }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-secrets
                  key: {{ $key | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.env.LIVE_PORT }}
            initialDelaySeconds: 60
            periodSeconds: 10